$VersionControl = 'git'
$VersionControlRepos = @(
    'https://github.com/pip-webui/pip-webui-lib.git'
    'https://github.com/pip-webui/pip-webui-css.git'
    'https://github.com/pip-webui/pip-webui-services.git'
    'https://github.com/pip-webui/pip-webui-behaviors.git'
    'https://github.com/pip-webui/pip-webui-themes.git'
    'https://github.com/pip-webui/pip-webui-buttons.git'
    'https://github.com/pip-webui/pip-webui-headers.git'
    'https://github.com/pip-webui/pip-webui-lists.git'
    'https://github.com/pip-webui/pip-webui-dates.git'
    'https://github.com/pip-webui/pip-webui-controls.git'
    'https://github.com/pip-webui/pip-webui-landing.git'
    'https://github.com/pip-webui/pip-webui-charts.git'
    'https://github.com/pip-webui/pip-webui-dialogs.git'
    'https://github.com/pip-webui/pip-webui-layouts.git'
    'https://github.com/pip-webui/pip-webui-nav.git'
    'https://github.com/pip-webui/pip-webui-errors.git'
    'https://github.com/pip-webui/pip-webui-locations.git'
    'https://github.com/pip-webui/pip-webui-files.git'
    'https://github.com/pip-webui/pip-webui-settings.git'
    'https://github.com/pip-webui/pip-webui-dashboard.git'
    'https://github.com/pip-webui/pip-webui-help.git'
    'https://github.com/pip-webui/pip-webui-all.git'
)
$Package = 'npm'
$Build = 'none'
$Document = 'none'
$Test = 'none'
$Deploy = 'none'
